name: ioedge
favicon: null
layout_spectrum: 0.7288814184721559
typography_spectrum: 0.6220638731028885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.015215680934488773
  lightness: 0.16084193345159292
  saturation: 0.8076511910185218
  rhythmicContrast: 0.19134927773848176
purpose: []
